pointcloud_to_laserscan:
  ros__parameters:
    target_frame: "lidar_link"
    transform_tolerance: 0.01
    min_height: -0.1
    max_height: 0.5
    angle_min: -3.14159
    angle_max: 3.14159
    angle_increment: 0.0087
    scan_time: 0.1
    range_min: 1.0
    range_max: 100.0
    use_inf: true
    inf_epsilon: 1.0
